# Generated by Django 4.2.4 on 2023-11-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_queue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="current_queue_size",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="queue",
            name="queue_status",
            field=models.CharField(
                blank=True,
                choices=[("open", "OPEN"), ("closed", "CLOSED"), ("full", "FULL")],
                max_length=10,
            ),
        ),
    ]
