# Generated by Django 4.2.4 on 2023-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_queue", "0002_alter_slot_request_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slot",
            name="request_number",
        ),
        migrations.AddField(
            model_name="queue",
            name="request_number",
            field=models.IntegerField(default=1),
        ),
    ]
