# Generated by Django 4.2.4 on 2023-11-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_queue", "0002_alter_queue_current_queue_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="current_queue_size",
            field=models.IntegerField(blank=True),
        ),
    ]
