# Generated by Django 4.2.4 on 2023-11-28 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_queue", "0003_alter_queue_current_queue_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="queueparticipant",
            name="preferred_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
