# Generated by Django 4.2.4 on 2023-09-16 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("virtual_queue", "0003_delete_service_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="services",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("open", "OPEN"), ("closed", "CLOSED")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="estimated_wait_time",
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_details",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estimated_wait_time", models.PositiveIntegerField(blank=True)),
                ("current_wait_time", models.DateTimeField()),
                ("max_capacity", models.IntegerField()),
                (
                    "queue_status",
                    models.CharField(
                        blank=True,
                        choices=[("open", "OPEN"), ("closed", "CLOSED")],
                        max_length=10,
                    ),
                ),
                ("current_queue_size", models.IntegerField(max_length=200)),
                ("queue_start_time", models.DateTimeField()),
                ("queue_end_time", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, max_length=400)),
                (
                    "participants",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_queue.services",
                    ),
                ),
            ],
        ),
    ]
