# Generated by Django 4.2.4 on 2023-08-10 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("desc", models.TextField(blank=True, null=True)),
                ("source_link", models.CharField(max_length=2000)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
